/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as PrivacyTermsRouteImport } from './routes/privacy-terms'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as NewslettersIndexRouteImport } from './routes/newsletters.index'
import { Route as NewslettersSlugRouteImport } from './routes/newsletters.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyTermsRoute = PrivacyTermsRouteImport.update({
  id: '/privacy-terms',
  path: '/privacy-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const NewslettersIndexRoute = NewslettersIndexRouteImport.update({
  id: '/newsletters/',
  path: '/newsletters/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewslettersSlugRoute = NewslettersSlugRouteImport.update({
  id: '/newsletters/$slug',
  path: '/newsletters/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/our-story': typeof OurStoryRoute
  '/privacy-terms': typeof PrivacyTermsRoute
  '/resources': typeof ResourcesRoute
  '/account': typeof AuthenticatedAccountRoute
  '/newsletters/$slug': typeof NewslettersSlugRoute
  '/newsletters/': typeof NewslettersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/our-story': typeof OurStoryRoute
  '/privacy-terms': typeof PrivacyTermsRoute
  '/resources': typeof ResourcesRoute
  '/account': typeof AuthenticatedAccountRoute
  '/newsletters/$slug': typeof NewslettersSlugRoute
  '/newsletters': typeof NewslettersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/our-story': typeof OurStoryRoute
  '/privacy-terms': typeof PrivacyTermsRoute
  '/resources': typeof ResourcesRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/newsletters/$slug': typeof NewslettersSlugRoute
  '/newsletters/': typeof NewslettersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/faq'
    | '/our-story'
    | '/privacy-terms'
    | '/resources'
    | '/account'
    | '/newsletters/$slug'
    | '/newsletters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/faq'
    | '/our-story'
    | '/privacy-terms'
    | '/resources'
    | '/account'
    | '/newsletters/$slug'
    | '/newsletters'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/faq'
    | '/our-story'
    | '/privacy-terms'
    | '/resources'
    | '/_authenticated/account'
    | '/newsletters/$slug'
    | '/newsletters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FaqRoute: typeof FaqRoute
  OurStoryRoute: typeof OurStoryRoute
  PrivacyTermsRoute: typeof PrivacyTermsRoute
  ResourcesRoute: typeof ResourcesRoute
  NewslettersSlugRoute: typeof NewslettersSlugRoute
  NewslettersIndexRoute: typeof NewslettersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-terms': {
      id: '/privacy-terms'
      path: '/privacy-terms'
      fullPath: '/privacy-terms'
      preLoaderRoute: typeof PrivacyTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/newsletters/': {
      id: '/newsletters/'
      path: '/newsletters'
      fullPath: '/newsletters/'
      preLoaderRoute: typeof NewslettersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletters/$slug': {
      id: '/newsletters/$slug'
      path: '/newsletters/$slug'
      fullPath: '/newsletters/$slug'
      preLoaderRoute: typeof NewslettersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FaqRoute: FaqRoute,
  OurStoryRoute: OurStoryRoute,
  PrivacyTermsRoute: PrivacyTermsRoute,
  ResourcesRoute: ResourcesRoute,
  NewslettersSlugRoute: NewslettersSlugRoute,
  NewslettersIndexRoute: NewslettersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
